### ISSUE TITLE
最近正好需要！太感谢啦！

### ISSUE THREAD

**Issue by JonnesLin** [gitabtion/ConvBert-PyTorch#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gitabtion** [comment]
荣幸之至，不过代码有1处是跟开源的tf版本的代码是有冲突的，原文中为了适配不同的self attention压缩比率，在mixed attention layer的最后设置了两linear用于映射到所需维度，在官方的开源代码中，他们将比率固定为2，并舍弃了这两个用于映射的linear，而我是按paper复现的，保留了这两个linear。此外，transformers官方的代码有convbert分支，可以关注一下。

**Comment by JonnesLin** [comment]
好滴，感谢！
